"""add_legal_documents

Revision ID: b4b2538d71e3
Revises: 
Create Date: 2026-05-12 17:11:43.908091
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'b4b2538d71e3'
down_revision: Union[str, None] = 'a0_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legal_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_number', sa.String(length=100), nullable=True),
    sa.Column('doc_type', sa.Enum('PROPOSAL', 'BERITA_ACARA', 'SURAT_JALAN', 'OTHER', name='doctype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'SIGNED', 'REJECTED', name='docstatus'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('recipient_name', sa.String(length=255), nullable=True),
    sa.Column('recipient_company', sa.String(length=255), nullable=True),
    sa.Column('recipient_address', sa.Text(), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('closing', sa.Text(), nullable=True),
    sa.Column('quoted_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('rejection_note', sa.Text(), nullable=True),
    sa.Column('signed_by', sa.Integer(), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['signed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_legal_docs_created_by', 'legal_documents', ['created_by'], unique=False)
    op.create_index('ix_legal_docs_status', 'legal_documents', ['status'], unique=False)
    op.create_index('ix_legal_docs_type', 'legal_documents', ['doc_type'], unique=False)
    op.create_index(op.f('ix_legal_documents_doc_number'), 'legal_documents', ['doc_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_legal_documents_doc_number'), table_name='legal_documents')
    op.drop_index('ix_legal_docs_type', table_name='legal_documents')
    op.drop_index('ix_legal_docs_status', table_name='legal_documents')
    op.drop_index('ix_legal_docs_created_by', table_name='legal_documents')
    op.drop_table('legal_documents')
    # ### end Alembic commands ###
